### PR TITLE
fix(Grid.js): ScrollIfNecessary does not account for scrollWidth correctly

### LINKED ISSUE #6653: 4.4.5: Infinite loop with cellnav and enableCellEditOnFocus
In ui-grid 4.4.5, with cell-nav and cell-edit features enabled with enableCellEditOnFocus set to true. 
Navigating to the last row in the grid gets stuck in an infinite loop (cpu in the tab goes often to 100%) or becomes un-editable

I am able to reproduce the error in the following plunker for both chrome and firefox.
Steps to reproduce: expand all rows, scroll to the bottom, select a cell in the bottom row
http://plnkr.co/edit/cVIvvBzZ6clPMEZzWAjr?p=preview

- [x] This is a bug report, not a question on how to use the grid.  
Use [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-ui-grid) or [Gitter](https://gitter.im/angular-ui/ui-grid) for questions.
- [x] You have searched the open issues to see if this bug has been filed before.  We don't want duplicate issues.
- [x] You have reviewed the tutorials and documentation to ensure you are using the grid correctly. [ui-grid.info](http://ui-grid.info/docs/#/tutorial)
- [x] You are using the latest version of the grid. Older versions are not patched or supported.
- [x] You have provided steps to recreate your bug.  A plunkr is even better.

### PR DESCRIPTION
**Pull request by m4m4m4**
Since scrollIfNecessary is called multiple times when enableCellEditOnFocus is true we need to make sure the scrollbarWidth and footerHeight is accounted for to not cause a loop.

fixes #6653

### CODE REVIEW

File: src/js/core/factories/Grid.js [hunk 1]
```diff
@@ -2444,6 +2444,11 @@ angular.module('ui.grid')
           //   to get the full position we need
           scrollPixels = self.renderContainers.body.prevScrollTop - (topBound - pixelsToSeeRow);
 
+          //Since scrollIfNecessary is called multiple times when enableCellEditOnFocus is true we need to make sure the scrollbarWidth and footerHeight is accounted for to not cause a loop.
+          if (gridCol.colDef.enableCellEditOnFocus === true) {
+            scrollPixels = scrollPixels - self.footerHeight - self.scrollbarWidth;
```
Comment (mportuga) [inline src/js/core/factories/Grid.js]: Is there a reason why we wouldn't want to check this every time? Why are we only checking for the footer and scroll bar when enableCellEditOnFocus is true?

Comment (m4m4m4) [reply src/js/core/factories/Grid.js]: The downside that I have found in leaving it on for everything is that it will scroll a bit too much for the grids not using enableCellEditOnFocus. It makes navigating by keys not appear as smooth and that might make it confusing.

Comment (mportuga) [reply src/js/core/factories/Grid.js]: Hmm, I see, makes sense. Also, as a follow up, could you add a null or undefined check for gridCol instead of assuming it will be there. I ask, because i noticed that a few lines now, we are checking for that and I don't want this to ever blow up on users of this function. I believe refactoring it to the following should work:

`if (gridCol && gridCol.colDef && gridCol.colDef.enableCellEditOnFocus) {`

There should be no need to explicitly compare enableCellEditOnFocus to true either.
