### PR TITLE
fix(core): Sort Priority Zero Based

### LINKED ISSUE #4685: Sort number does not start from 0 when there is default sorted column ui-grid 3.0
When sorting is enabled by default for a column, the sorting number is 0. -> OK
But when I clicked another column, the sorting number changes to 1 while there is only one sorted column. -> It should be 0.

See this plunker:
http://plnkr.co/edit/q0Dhe9MLzgteYqdjtq6r?p=preview

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Before sort priority was a mix of 0 and 1 based.
You could create columns with a sort priority of zero but once the user
clicked on a column to sort it its index would change to 1. There was no
way for the sort index to return to 0 from within the grid's menus.
This mix of 0 and 1 based sorting was confusing and created UI problems
when displaying the sort index in the column header.

Closes #4685
BREAKING CHANGE:
**GridOptions.columnDef.sort.priority** now expects the lowest value
to be 0.
The Grid Header will display a sort priority of 0 as 1.
Using `if(col.sort.priority)` to determine if a column is sorted is no
longer valid as `0 == false`.
Saved grid objects may be affected by this.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
This has a breaking change. It would be good to do a version bump to 3.1.0 after this is merged.

File: src/js/core/factories/Grid.js [hunk 1]
```diff
@@ -1876,12 +1876,12 @@ angular.module('ui.grid')
         p = 0;
 
     self.columns.forEach(function (col) {
-      if (col.sort && col.sort.priority && col.sort.priority > p) {
-        p = col.sort.priority;
+      if (col.sort && col.sort.priority !== 'undefined' && col.sort.priority >= p) {
```
Comment (imbalind) [inline src/js/core/factories/Grid.js]: I think here you should compare `col.sort.priority` to `undefined` and not `'undefined'` or `typeof col.sort.priority === 'undefined'`

Comment (JLLeitschuh) [inline src/js/core/factories/Grid.js]: Thanks! I'll change that. I saw it like this somewhere else.

**Comment by swalters** [comment]
@JLLeitschuh can you fix the merge issues?  I think we need to get this merged and released as soon as we can. thanks.

**Comment by JLLeitschuh** [comment]
Yea, I'll try to fix this tonight.

File: src/templates/ui-grid/uiGridHeaderCell.html [hunk 2]
```diff
@@ -21,13 +21,13 @@
       aria-label="{{getSortDirectionAriaLabel()}}">
       <i
        ng-class="{ 'ui-grid-icon-up-dir': col.sort.direction == asc, 'ui-grid-icon-down-dir': col.sort.direction == desc, 'ui-grid-icon-blank': !col.sort.direction }"
-       title="{{isSortPriorityVisible() ? i18n.headerCell.priority + ' ' + col.sort.priority : null}}"
+       title="{{isSortPriorityVisible() ? i18n.headerCell.priority + ' ' + ( col.sort.priority + 1 )  : null}}"
```
Comment (dlgski) [inline src/templates/ui-grid/uiGridHeaderCell.html]: In Grid.js line 1880 aren't you bumping up the sortPriority, so adding 1 again here would be incorrect?

File: src/templates/ui-grid/uiGridHeaderCell.html [hunk 3]
```diff
@@ -21,13 +21,13 @@
...
        aria-hidden="true">
      </i>
      <sub
        ui-grid-visible="isSortPriorityVisible()"
        class="ui-grid-sort-priority-number">
-       {{col.sort.priority}}
+       {{col.sort.priority + 1}}
```
Comment (dlgski) [inline src/templates/ui-grid/uiGridHeaderCell.html]: same as above
